name: Alphalcazar

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - 'master'
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  test-cpp:
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest

        include:
          - os: windows-latest
            shell: powershell
            env_cc: cl.exe
            env_cxx: cl.exe

          - os: ubuntu-latest
            shell: bash
            env_cc: clang
            env_cxx: clang++
  
    name: Test (C++17 - ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell }}

    steps:
    - uses: actions/checkout@v2
    - name: Configure command prompt for MSVC++
      uses: ilammy/msvc-dev-cmd@v1
      if: matrix.os == 'windows-latest'
    - name: Set up Python 3.10
      uses: actions/setup-python@v6
      with:
        python-version: 3.10
    - name: Install latest conan 2 version
      run: |
        pip install --upgrade wheel
        pip install --upgrade "conan<3"
    - name: Install conan dependencies
      run: |
        conan install . -s build_type=Release --build=missing --output-folder='${{ runner.temp }}/build/${{ runner.os }}'
    - name: Build with CMake
      uses: lukka/run-cmake@v10
      env:
        CC: ${{ matrix.env_cc }}
        CXX: ${{ matrix.env_cxx }}
      with:
        buildDirectory: '${{ runner.temp }}/build/${{ runner.os }}'
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: '${{ github.workspace }}/cpp/CMakeLists.txt'
        cmakeAppendedArgs: "-G Ninja -DCMAKE_BUILD_TYPE=Release"
    - name: Test
      run: |
        cd '${{ runner.temp }}/build/${{ runner.os }}'
        ctest -C Release --timeout 600 -V

  test-python:
    name: Test (Python)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v6
      with:
        python-version: 3.10
    - name: Install dependencies
      run: |
        cd python_deprecated
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        cd python_deprecated
        pytest
